sudo: false
language: ruby
script: "bundle exec rake ci"
env:
  - TRAVIS=true
rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
notifications:
  irc:
    channels:
      - irc.freenode.org#mutant
    on_success: never
    on_failure: change
