---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude: []
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: false
  exclude: []
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: true
  exclude:
  - Mutant::Matcher::Method::Singleton#receiver?
  - Mutant::Matcher::Method::Instance#match?
  - Mutant::CLI#parse
  - Mutant::Mutation::Evil#success?
  - Mutant::Mutation::Neutral#success?
  - Mutant::Reporter::CLI#subject_results
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude:
  - Mutant::Matcher::Method::Instance#self.build?
  max_params: 2
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
  - Mutant#self.singleton_subclass_instance
  - Mutant::Mutator::Util::Array::Element#dispatch
  - Mutant::CLI#parse
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: false
RepeatedConditional:
  enabled: true
  exclude:
  - Mutant::Mutator
  - Mutant::Reporter::CLI
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Mutant::CLI     # 4 vars
  - Mutant::Killer  # 4 vars
  - Mutant::Mutator # 4 vars
  - Mutant::Runner  # 4 vars
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
  - Mutant::CLI
  - Mutant::Reporter::CLI
  max_methods: 10
TooManyStatements:
  enabled: true
  exclude:
  - Mutant::CLI#parse
  - Mutant::Reporter::CLI#colorized_diff
  - Mutant::Reporter::CLI::Printer::Config::Runner#run
  - Mutant#self.singleton_subclass_instance
  - Mutant::Zombifier::File#self.find_uncached
  - Mutant::Runner#dispatch
  max_statements: 6
UncommunicativeMethodName:
  enabled: true
  exclude:
  - Mutant::Mutation#sha1
  - Mutant::NodeHelpers#s
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - Mutant::NodeHelpers#s
  - Mutant::CLI#reporter
  - Mutant::Mutation::Evil#success?
  - Mutant::Mutation::Neutral#success?
  max_helper_calls: 0
