---
Attribute:
  enabled: false
  exclude: []
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude:
  - Mutant::Expression#match_length
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: false
  exclude: []
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: true
  exclude:
  - Mutant::Matcher::Method::Instance#match?
  - Mutant::Matcher::Method::Singleton#receiver?
  - Mutant::Mutation::Evil#success?
  - Mutant::Mutation::Neutral#success?
  - Mutant::Reporter::CLI#subject_results
  - Mutant::Rspec::Strategy#options
  # Nature of OptionParser :(
  - Mutant::CLI#add_environmental_options
  - Mutant::CLI#parse
  # False positive, its a utility
  - Mutant::Meta::Example::Verification#format_mutation
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude:
  - Mutant::Matcher::Method::Instance#self.build?
  - Mutant::Runner#self.run
  max_params: 2
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude:
  - Mutant#self.singleton_subclass_instance
  - Mutant::CLI#parse
  - Mutant::Mutator::Util::Array::Element#dispatch
  - Mutant::Mutator::Node::Resbody#mutate_captures
  - Mutant::Mutator::Node::Arguments#emit_argument_mutations
  - Mutant::Reporter::CLI::Report::Config#generic_stats
  - Mutant::RequireHighjack#infect
  - Mutant::RequireHighjack#desinfect
  - Mutant::Reporter::CLI::Registry#included
  - Mutant::Strategy#tests
  - Parser::Lexer#self.new
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: false
RepeatedConditional:
  enabled: true
  exclude:
  - Mutant::Mutator
  - Mutant::Rspec::Strategy
  - Mutant::Reporter::CLI
  - Mutant::Meta::Example::DSL
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Mutant::CLI     # 4 vars
  - Mutant::Killer  # 4 vars
  - Mutant::Mutator # 4 vars
  - Mutant::Runner  # 4 vars
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
  - Mutant::CLI
  - Mutant::Mutator::Node
  - Mutant::Reporter::CLI
  - Mutant::Meta::Example::Verification
  max_methods: 10
TooManyStatements:
  enabled: true
  exclude:
  - Mutant#self.singleton_subclass_instance
  - Mutant::Isolation#self.call
  - Mutant::Rspec::Killer#run
  - Mutant::Reporter::CLI#colorized_diff
  - Mutant::Reporter::CLI::Report::Config#run
  - Mutant::Runner#visit_collection
  - Mutant::Runner#initialize
  - Mutant::Runner::Mutation#run
  - Mutant::Zombifier::File#self.find
  - Mutant::RequireHighjack#infect
  - Mutant::Reporter::CLI::Registry#included
  - Mutant::Rspec::Strategy#new_reporter
  - Mutant::Rspec::Strategy#run
  # How mutant does CLI parsing is shit
  - Mutant::CLI#parse
  - Mutant::CLI#initialize
  - Mutant::CLI#add_debug_options
  max_statements: 6
UncommunicativeMethodName:
  enabled: true
  exclude:
  - Mutant::Mutation#sha1
  - Mutant::NodeHelpers#s
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: ['force_utf32']
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - Mutant::CLI#reporter
  - Mutant::Mutation::Evil#success?
  - Mutant::Mutation::Neutral#success?
  - Mutant::NodeHelpers#s
  - Mutant::Rspec::Strategy#configuration
  - Mutant::Rspec::Strategy#example_groups
  - Mutant::Rspec::Strategy#options
  - Mutant::Rspec::Strategy#world
  - Mutant::Rspec::Strategy#rspec2
  - Mutant::Meta::Example::Verification#format_mutation
  max_helper_calls: 0
