---
AbcMetricMethodCheck:
  score: 12.1
AssignmentInConditionalCheck:    {}
CaseMissingElseCheck:            {}
ClassLineCountCheck:
  line_count: 200
ClassNameCheck:                  
  pattern: !ruby/regexp /\A(?:[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/
ClassVariableCheck:              {}
CyclomaticComplexityBlockCheck:
  complexity: 2
CyclomaticComplexityMethodCheck:
  complexity: 3
EmptyRescueBodyCheck:            {}
ForLoopCheck:                    {}
MethodLineCountCheck:
  line_count: 9
MethodNameCheck:
  pattern: !ruby/regexp /\A(?:[a-z\d](?:_?[a-z\d])+[?!=]?|\[\]=?|==|<=>|<<|[+*&|-])\z/
ModuleLineCountCheck:
  line_count: 202
ModuleNameCheck:
  pattern: !ruby/regexp /\A(?:[A-Z]+|[A-Z][a-z](?:[A-Z]?[a-z])+)\z/
ParameterNumberCheck:
  parameter_count: 2
